// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuufkYym67ttzTAPcj3swEN4c3Ys7R40o',
    appId: '1:1082908221478:web:83f74efb348ed71cfb86e7',
    messagingSenderId: '1082908221478',
    projectId: 'tala-trip-app',
    authDomain: 'tala-trip-app.firebaseapp.com',
    storageBucket: 'tala-trip-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6eJA3_x3mVVJOiKF1KW8bsaGwhWrWQiU',
    appId: '1:1082908221478:android:60974c673a7ff841fb86e7',
    messagingSenderId: '1082908221478',
    projectId: 'tala-trip-app',
    storageBucket: 'tala-trip-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj6VMi2RDiQgzBSonsILhXn7jHM3fPdXs',
    appId: '1:1082908221478:ios:b8bd4ed46e5417bdfb86e7',
    messagingSenderId: '1082908221478',
    projectId: 'tala-trip-app',
    storageBucket: 'tala-trip-app.firebasestorage.app',
    iosClientId: '1082908221478-h3rt84pn5tnnqc7cpkv6rqsth38qa8r3.apps.googleusercontent.com',
    iosBundleId: 'com.example.talaTripApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj6VMi2RDiQgzBSonsILhXn7jHM3fPdXs',
    appId: '1:1082908221478:ios:b8bd4ed46e5417bdfb86e7',
    messagingSenderId: '1082908221478',
    projectId: 'tala-trip-app',
    storageBucket: 'tala-trip-app.firebasestorage.app',
    iosClientId: '1082908221478-h3rt84pn5tnnqc7cpkv6rqsth38qa8r3.apps.googleusercontent.com',
    iosBundleId: 'com.example.talaTripApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuufkYym67ttzTAPcj3swEN4c3Ys7R40o',
    appId: '1:1082908221478:web:34048af5096094b4fb86e7',
    messagingSenderId: '1082908221478',
    projectId: 'tala-trip-app',
    authDomain: 'tala-trip-app.firebaseapp.com',
    storageBucket: 'tala-trip-app.firebasestorage.app',
  );
}
